[-1338]
func_addr = 36944
name = "a2"
stack_offset = -4920
stack_offset_type = 1
size = 8
type = "time_t"
last_change = 1628117489

[-1328]
func_addr = 36944
name = "a3"
stack_offset = -4904
stack_offset_type = 1
size = 56
type = "struct tm"
last_change = 1628117481

[-12e8]
func_addr = 36944
name = "v70"
stack_offset = -4840
stack_offset_type = 1
size = 56
type = "struct tm"
last_change = 1628117492
