[6800]
addr = 26624
name = "deregister_tm_clones"
last_change = 1628119157

[6830]
addr = 26672
name = "register_tm_clones"
last_change = 1628119160

[68b0]
addr = 26800
name = "j_register_tm_clones"
last_change = 1628119163

[6870]
addr = 26736
name = "__do_global_dtors_aux"
last_change = 1628119168

[6910]
addr = 26896
name = "get_funky_string"
last_change = 1628119172

[6b40]
addr = 27456
name = "is_colored"
last_change = 1628119175

[6bb0]
addr = 27568
name = "set_line_length"
last_change = 1628119180

[6c30]
addr = 27696
name = "abformat_init"
last_change = 1628119184

[6e80]
addr = 28288
name = "queue_directory"
last_change = 1628119187

[6f20]
addr = 28448
name = "free_ent"
last_change = 1628119192

[6f70]
addr = 28528
name = "clear_files"
last_change = 1628119196

[7020]
addr = 28704
name = "needs_quoting"
last_change = 1628119199

[70a0]
addr = 28832
name = "file_escape"
last_change = 1628119206

[7180]
addr = 29056
name = "sort_files"
last_change = 1628119210

[7310]
addr = 29456
name = "xstrcoll"
last_change = 1628119213

[7390]
addr = 29584
name = "extract_dirs_from_files"
last_change = 1628119218

[7520]
addr = 29984
name = "indent"
last_change = 1628119222

[75f0]
addr = 30192
name = "dired_dump_obstack"
last_change = 1628119225

[76c0]
addr = 30400
name = "format_user_or_group"
last_change = 1628119230

[7780]
addr = 30592
name = "format_user"
last_change = 1628119235

[77f0]
addr = 30704
name = "file_failure"
last_change = 1628119239

[7860]
addr = 30816
name = "strcmp_size"
last_change = 1628119244

[78a0]
addr = 30880
name = "xstrcoll_df_name"
last_change = 1628119247

[7900]
addr = 30976
name = "xstrcoll_df_name_0"
last_change = 1628119251

[7960]
addr = 31072
name = "rev_xstrcoll_df_name"
last_change = 1628119255

[79d0]
addr = 31184
name = "rev_strcmp_df_name"
last_change = 1628119259

[7a40]
addr = 31296
name = "get_type_indicator"
last_change = 1628119264

[7b30]
addr = 31536
name = "print_type_indicator"
last_change = 1628119268

[7b80]
addr = 31616
name = "strcmp_df_atime"
last_change = 1628119272

[7cd0]
addr = 31952
name = "rev_strcmp_df_extension"
last_change = 1628119275

[7dc0]
addr = 32192
name = "signal_setup"
last_change = 1628119281

[7f90]
addr = 32656
name = "prep_non_filename_text"
last_change = 1628119284

[7ff0]
addr = 32752
name = "put_indicator"
last_change = 1628119288

[8060]
addr = 32864
name = "restore_default_color"
last_change = 1628119293

[8090]
addr = 32912
name = "process_signals"
last_change = 1628119300

[8170]
addr = 33136
name = "set_normal_color"
last_change = 1628119305

[81e0]
addr = 33248
name = "quote_name_buf"
last_change = 1628119308

[8650]
addr = 34384
name = "quote_name"
last_change = 1628119312

[8a60]
addr = 35424
name = "print_name_with_quoting"
last_change = 1628119316

[8eb0]
addr = 36528
name = "print_file_name_and_frills"
last_change = 1628119324

[9ab0]
addr = 39600
name = "quote_name_width"
last_change = 1628119329

[9b50]
addr = 39760
name = "length_of_file_name_and_frills"
last_change = 1628119336

[9d00]
addr = 40192
name = "calculate_columns"
last_change = 1628119341

[9fe0]
addr = 40928
name = "print_with_separator"
last_change = 1628119344

[a1a0]
addr = 41376
name = "print_current_files"
last_change = 1628119348

[a530]
addr = 42288
name = "rev_strcmp_df_size"
last_change = 1628119353

[a5b0]
addr = 42416
name = "strcmp_size_0"
last_change = 1628119356

[a5f0]
addr = 42480
name = "xstrcoll_df_size"
last_change = 1628119360

[a670]
addr = 42608
name = "xstrcoll_df_size_0"
last_change = 1628119365

[a6f0]
addr = 42736
name = "rev_strcmp_df_size_0"
last_change = 1628119368

[a770]
addr = 42864
name = "rev_xstrcoll_size"
last_change = 1628119371

[a7b0]
addr = 42928
name = "rev_xstrcoll_size_0"
last_change = 1628119376

[a7f0]
addr = 42992
name = "strcmp_df_ctime"
last_change = 1628119379

[a880]
addr = 43136
name = "strcmp_df_mtime"
last_change = 1628119384

[a900]
addr = 43264
name = "format_user_width"
last_change = 1628119389

[a9d0]
addr = 43472
name = "gobble_file"
last_change = 1628119392

[b8c0]
addr = 47296
name = "print_dir"
last_change = 1628119396

[bfc0]
addr = 49088
name = "rev_xstrcoll_ctime"
last_change = 1628119401

[c010]
addr = 49168
name = "rev_xstrcoll_atime"
last_change = 1628119404

[c060]
addr = 49248
name = "xstrcoll_ctime"
last_change = 1628119408

[c0b0]
addr = 49328
name = "xstrcoll_mtime"
last_change = 1628119413

[c0f0]
addr = 49392
name = "rev_xstrcoll_mtime"
last_change = 1628119416

[c140]
addr = 49472
name = "xstrcoll_atime"
last_change = 1628119420

[c180]
addr = 49536
name = "rev_xstrcoll_df_atime"
last_change = 1628119424

[c210]
addr = 49680
name = "strcmp_df_mtime_0"
last_change = 1628119428

[c290]
addr = 49808
name = "strcmp_df_ctime_0"
last_change = 1628119432

[c320]
addr = 49952
name = "rev_xstrcoll_df_mtime"
last_change = 1628119436

[c3b0]
addr = 50096
name = "rev_xstrcoll_df_ctime"
last_change = 1628119440

[c450]
addr = 50256
name = "strcmp_df_atime_0"
last_change = 1628119444

[c4d0]
addr = 50384
name = "xstrcoll_mtime_0"
last_change = 1628119449

[c510]
addr = 50448
name = "rev_xstrcoll_mtime_0"
last_change = 1628119453

[c560]
addr = 50528
name = "xstrcoll_ctime_0"
last_change = 1628119456

[c5b0]
addr = 50608
name = "rev_xstrcoll_atime_0"
last_change = 1628119461

[c600]
addr = 50688
name = "xstrcoll_atime_0"
last_change = 1628119464

[c640]
addr = 50752
name = "rev_xstrcoll_ctime_0"
last_change = 1628119468

[c690]
addr = 50832
name = "rev_xstrcoll_df_atime_0"
last_change = 1628119472

[c720]
addr = 50976
name = "rev_xstrcoll_df_mtime_0"
last_change = 1628119476

[c7b0]
addr = 51120
name = "rev_xstrcoll_df_ctime_0"
last_change = 1628119479

[c850]
addr = 51280
name = "xstrcoll_extension"
last_change = 1628119484

[c8c0]
addr = 51392
name = "rev_xstrcoll_extension"
last_change = 1628119487

[c930]
addr = 51504
name = "xstrcoll_df_extension"
last_change = 1628119491

[c9f0]
addr = 51696
name = "rev_xstrcoll_df_extension"
last_change = 1628119495

[cab0]
addr = 51888
name = "strcmp_extension"
last_change = 1628119499

[cb30]
addr = 52016
name = "rev_strcmp_extension"
last_change = 1628119504

[cbb0]
addr = 52144
name = "strcmp_df_extension"
last_change = 1628119508

[cca0]
addr = 52384
name = "usage"
last_change = 1628119512

[d3e0]
addr = 54240
name = "areadlink_with_size"
last_change = 1628119515

[d4e0]
addr = 54496
name = "argmatch"
last_change = 1628119520

[d5f0]
addr = 54768
name = "argmatch_invalid"
last_change = 1628119523

[d680]
addr = 54912
name = "argmatch_valid"
last_change = 1628119527

[d7b0]
addr = 55216
name = "__xargmatch_internal"
last_change = 1628119531

[d890]
addr = 55440
name = "c_strncasecmp"
last_change = 1628119535

[d900]
addr = 55552
name = "canonicalize_filename_mode"
last_change = 1628119539

[dfe0]
addr = 57312
name = "close_stdout"
last_change = 1628119543

[e090]
addr = 57488
name = "dir_len"
last_change = 1628119547

[e0d0]
addr = 57552
name = "mdir_name"
last_change = 1628119550

[e140]
addr = 57664
name = "last_component"
last_change = 1628119555

[e1a0]
addr = 57760
name = "base_len"
last_change = 1628119558

[e1d0]
addr = 57808
name = "file_has_acl"
last_change = 1628119562

[e290]
addr = 58000
name = "record_file"
last_change = 1628119566

[e320]
addr = 58144
name = "seen_file"
last_change = 1628119570

[e530]
addr = 58672
name = "mfile_name_concat"
last_change = 1628119573
