[struct_metadata]
name = "timezone_string_thing"
size = 9
last_change = 1628118131

[0]
member_name = "field_0"
offset = 0
type = ""
size = 8

[8]
member_name = "includes_string"
offset = 8
type = ""
size = 1

[9]
member_name = "string_buf"
offset = 9
type = ""
size = 0
