[struct_metadata]
name = "timezone_string_thing"
size = 9
last_change = 1628117182

[0]
member_name = "field_0"
offset = 0
type = ""
size = 4

[4]
member_name = "field_4"
offset = 4
type = ""
size = 4

[8]
member_name = "field_8"
offset = 8
type = ""
size = 1
